output = "models"
wipe = true
no-tests = true
no-context = true

[mysql]
dbname  = "pluto"
host    = "127.0.0.1"
port    = 3307
user    = "root"
pass    = "test"
sslmode = "false"

#[imports.all]
  #third_party = ['"github.com/volatiletech/null"']
